create table if not exists public.general_cards (
  id text primary key,
  page integer not null,
  slot integer not null,
  name text not null,
  stars integer default 1,
  default_frame text default 'basic',
  image_url text
);

create table if not exists public.player_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  card_id text not null,
  count integer default 0,
  unique(user_id, card_id)
);

-- Ajustes sobre las tablas que ya creaste.
alter table public.general_cards
add column if not exists image_url text;

-- Para la miniatura/fondo de cada pagina del album.
create table if not exists public.page_images (
  page integer primary key,
  image_url text not null
);

alter table public.general_cards enable row level security;
alter table public.player_progress enable row level security;
alter table public.page_images enable row level security;

drop policy if exists "Acceso Publico general_cards" on public.general_cards;
drop policy if exists "Acceso Publico player_progress" on public.player_progress;
drop policy if exists "Acceso Publico page_images" on public.page_images;

create policy "Acceso Publico general_cards"
on public.general_cards
for all
using (true)
with check (true);

create policy "Acceso Publico player_progress"
on public.player_progress
for all
using (true)
with check (true);

create policy "Acceso Publico page_images"
on public.page_images
for all
using (true)
with check (true);

-- Bucket usado por la app. Si ya existe, no cambia nada.
insert into storage.buckets (id, name, public)
values ('card-images', 'card-images', true)
on conflict (id) do nothing;

drop policy if exists "Carga Publica de Imagenes" on storage.objects;
drop policy if exists "Lectura Publica de Imagenes" on storage.objects;

create policy "Carga Publica de Imagenes"
on storage.objects
for insert
with check (bucket_id = 'card-images');

create policy "Lectura Publica de Imagenes"
on storage.objects
for select
using (bucket_id = 'card-images');
