create table if not exists public.general_cards (
  id text primary key,
  page integer not null,
  slot integer not null,
  name text not null,
  stars integer default 1,
  default_frame text default 'basic',
  image_url text
);

create table if not exists public.player_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  card_id text not null,
  count integer default 0,
  unique(user_id, card_id)
);

-- Ajustes sobre las tablas que ya creaste.
alter table public.general_cards
add column if not exists image_url text;

-- Para la miniatura/fondo de cada pagina del album.
create table if not exists public.page_images (
  page integer primary key,
  image_url text not null
);

alter table public.general_cards enable row level security;
alter table public.player_progress enable row level security;
alter table public.page_images enable row level security;

drop policy if exists "Acceso Publico general_cards" on public.general_cards;
drop policy if exists "Acceso Publico player_progress" on public.player_progress;
drop policy if exists "Acceso Publico page_images" on public.page_images;

create policy "Acceso Publico general_cards"
on public.general_cards
for all
using (true)
with check (true);

create policy "Acceso Publico player_progress"
on public.player_progress
for all
using (true)
with check (true);

create policy "Acceso Publico page_images"
on public.page_images
for all
using (true)
with check (true);

-- Bucket usado por la app. Si ya existe, no cambia nada.
insert into storage.buckets (id, name, public)
values ('card-images', 'card-images', true)
on conflict (id) do nothing;

drop policy if exists "Carga Publica de Imagenes" on storage.objects;
drop policy if exists "Lectura Publica de Imagenes" on storage.objects;

create policy "Carga Publica de Imagenes"
on storage.objects
for insert
with check (bucket_id = 'card-images');

create policy "Lectura Publica de Imagenes"
on storage.objects
for select
using (bucket_id = 'card-images');

-- Usuarios
create table if not exists public.users (
  uid text primary key,
  name text not null,
  pin text not null,
  is_admin boolean default false
);

create table if not exists public.admin_board_entries (
  id bigint generated by default as identity primary key,
  uid text not null unique,
  stat0 integer default 0,
  stat1 integer default 0,
  stat2 integer default 0,
  stat3 integer default 0,
  stat4 integer default 0,
  created_at timestamp with time zone default now()
);

alter table public.users enable row level security;
alter table public.admin_board_entries enable row level security;

drop policy if exists "Acceso Publico users" on public.users;
drop policy if exists "Acceso Publico admin_board_entries" on public.admin_board_entries;

create policy "Acceso Publico users"
on public.users
for all
using (true)
with check (true);

create policy "Acceso Publico admin_board_entries"
on public.admin_board_entries
for all
using (true)
with check (true);

-- Insertar admins iniciales
insert into public.users (uid, name, pin, is_admin)
values
  ('10589616', 'Vaiu', '0001', true),
  ('11327427', 'Cleme', '1132', true),
  ('11740250', 'GG', '1174', true),
  ('11845510', 'limon', '1184', true)
on conflict (uid) do nothing;
